name: travellingo
description: "Travellingo application"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0
  provider:
  google_fonts:
  flutter_launcher_icons: ^0.13.1
  local_auth: ^2.2.0
  dio: ^5.4.2+1
  rxdart: ^0.27.7
  dotted_border: ^2.1.0
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.8
  jwt_decoder: ^2.0.1
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo Travellingo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/Logo Travellingo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/Logo Travellingo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/Logo Travellingo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/flight/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#28527A"
  android_12:
    image: assets/Logo Splash.png
    icon_background_color: "#28527A"
    color: "#28527A"
